### ISSUE TITLE
Abao Tests Not Running

### ISSUE THREAD

**Issue by NikhilPunwaney** [cybertk/abao#242]
My Abao tests are not running: upon running the test, I get the message: Found Hookfiles: tests/raml/test_machines_hooks.js 

But none of the tests run as they did before. 

Nothing has changed about the hookfiles or the RAML. Please advise what could have caused this issue

**Comment by jtodo** [comment]
I have a similar problem.

My environment is version v 0.5.3, but the npm test fails.
It fails if version of underscore.js is 1.9.0, it does not seem to have failed in 1.8.3.

I’ll keep you posted.

**Comment by NikhilPunwaney** [comment]
The Abao version is 0.5.0
The Node version is v9.4.0
Platform is 
OS Version 10.12.6
API endpoint is running - verified using Postman

In the past, when I ran my command abao ../raml/api.raml --hookfiles=tests/raml/test_machines_hooks.js --server http://localhost:5000

Found Hookfiles: tests/raml/test_machines_hooks.js
  GET /batches -> 200
    ✓ Validate response code and body
.
.

However now I get:

Found Hookfiles: tests/raml/test_machines_hooks.js


  1) "before all" hook
  2) "after all" hook

  0 passing (6ms)
  2 failing

  1)  "before all" hook:
     TypeError: callback is not a function
      at /usr/local/lib/node_modules/abao/lib/hooks.coffee:76:16
      at /usr/local/lib/node_modules/abao/node_modules/async/dist/async.js:3888:9
      at /usr/local/lib/node_modules/abao/node_modules/async/dist/async.js:473:16
      at replenish (/usr/local/lib/node_modules/abao/node_modules/async/dist/async.js:1006:25)
      at /usr/local/lib/node_modules/abao/node_modules/async/dist/async.js:1016:9
      at eachOfLimit (/usr/local/lib/node_modules/abao/node_modules/async/dist/async.js:1041:24)
      at /usr/local/lib/node_modules/abao/node_modules/async/dist/async.js:1046:16
      at _parallel (/usr/local/lib/node_modules/abao/node_modules/async/dist/async.js:3879:5)
      at Object.series (/usr/local/lib/node_modules/abao/node_modules/async/dist/async.js:4735:5)
      at Hooks.runBeforeAll (/usr/local/lib/node_modules/abao/lib/hooks.coffee:75:20)
      at Hooks.runBeforeAll (/usr/local/lib/node_modules/abao/lib/hooks.coffee:3:59)
      at Object.mocha.suite.beforeAll._.bind.hooks (/usr/local/lib/node_modules/abao/lib/test-runner.coffee:103:31)
      at executeBound (/usr/local/lib/node_modules/abao/node_modules/underscore/underscore.js:758:67)
      at Context.<anonymous> (/usr/local/lib/node_modules/abao/node_modules/underscore/underscore.js:771:14)
      at Context.<anonymous> (/usr/local/lib/node_modules/abao/node_modules/underscore/underscore.js:122:29)

  2)  "after all" hook:
     TypeError: callback is not a function
      at /usr/local/lib/node_modules/abao/lib/hooks.coffee:82:16
      at /usr/local/lib/node_modules/abao/node_modules/async/dist/async.js:3888:9
      at /usr/local/lib/node_modules/abao/node_modules/async/dist/async.js:473:16
      at replenish (/usr/local/lib/node_modules/abao/node_modules/async/dist/async.js:1006:25)
      at /usr/local/lib/node_modules/abao/node_modules/async/dist/async.js:1016:9
      at eachOfLimit (/usr/local/lib/node_modules/abao/node_modules/async/dist/async.js:1041:24)
      at /usr/local/lib/node_modules/abao/node_modules/async/dist/async.js:1046:16
      at _parallel (/usr/local/lib/node_modules/abao/node_modules/async/dist/async.js:3879:5)
      at Object.series (/usr/local/lib/node_modules/abao/node_modules/async/dist/async.js:4735:5)
      at Hooks.runAfterAll (/usr/local/lib/node_modules/abao/lib/hooks.coffee:81:20)
      at Hooks.runAfterAll (/usr/local/lib/node_modules/abao/lib/hooks.coffee:3:59)
      at Object.mocha.suite.afterAll._.bind.hooks (/usr/local/lib/node_modules/abao/lib/test-runner.coffee:108:31)
      at executeBound (/usr/local/lib/node_modules/abao/node_modules/underscore/underscore.js:758:67)
      at Context.<anonymous> (/usr/local/lib/node_modules/abao/node_modules/underscore/underscore.js:771:14)
      at Context.<anonymous> (/usr/local/lib/node_modules/abao/node_modules/underscore/underscore.js:122:29)

In another branch, I only get Found Hookfiles: tests/raml/test_machines_hooks.js but am not sure what may cause the rest to stop.

I would like to run it as it was before. Right now it either doesn't run at all or throws the error as above.

**Comment by plroebuck** [comment]
@jtodo, you have the _exact_ same error, or something else?

@NikhilPunwaney, BTW, shouldn't your hookfile be named "test_batches_hooks.js" (format: "test_<endpoint>_hooks.js")

Can either of you provide me with a copy of something I can test locally? 
Would need hookfile, RAML, and copy of your endpoint code (abridged version would be fine).

**Comment by raj-bhagya** [comment]
Hi @plroebuck 
Here I attached the information you asked, sharing on be-half of @NikhilPunwaney . Please let me know if you need more details. 
[hooks_raml_blueprint_emb.zip](https://github.com/cybertk/abao/files/2045778/hooks_raml_blueprint_emb.zip)

**Comment by raj-bhagya** [comment]
@plroebuck ,

Are you able to reproduce the issue? FYI. the version and platform details were provided by @NikhilPunwaney in this thread.

**Comment by plroebuck** [comment]
@raj-bhagya, you sent a couple Python files but nothing that I could run myself. Unable to reproduce more than a portion of the required package, I can't do anything with what you provided.

**Abao-0.6.0** builds successfully with related patches to further lockdown dependency changes.
Install the new version and retry the test on your side.

**Comment by raj-bhagya** [comment]
@plroebuck , Our services are developed on Flask web application framework written in Python.

**Comment by raj-bhagya** [comment]
@plroebuck ,

I Installed latest development version **Abao-0.6.0**, but I'm encountering different error only with this version where as the previous version **0.5.0** is not throwing this error. I'm suspecting this could be because of node version compatibility, please suggest solution.

**0.6.0 Installation output:**
sudo npm install -g git+https://git@github.com/cybertk/abao.git#0.6.0
Password:
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
/usr/local/bin/abao -> /usr/local/lib/node_modules/abao/bin/abao
+ abao@0.6.0
added 173 packages from 569 contributors in 8.551s

[~/repos/simile → develop]$ **npm --version
6.1.0** 
[~/repos/simile → develop]$ **node -v
v10.2.1**

**Error:**
[~/repos/simile → develop]$ abao -v
path.js:39
    throw new ERR_INVALID_ARG_TYPE('path', 'string', path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.basename (path.js:1299:5)
    at parseArgs (/usr/local/lib/node_modules/abao/lib/cli.coffee:49:17)
    at Object.main (/usr/local/lib/node_modules/abao/lib/cli.coffee:67:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/abao/bin/abao:15:27)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)

**Comment by plroebuck** [comment]
@raj-bhagya, I don't get an error on my side (displays usage) but to display the version type:
```bash
$ abao --version
```

**Comment by raj-bhagya** [comment]
Same error with **abao --version**
[~/repos/simile/simile_web_service → develop]$ abao --version
path.js:39
    throw new ERR_INVALID_ARG_TYPE('path', 'string', path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.basename (path.js:1299:5)
    at parseArgs (/usr/local/lib/node_modules/abao/lib/cli.coffee:49:17)
    at Object.main (/usr/local/lib/node_modules/abao/lib/cli.coffee:67:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/abao/bin/abao:15:27)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)

**Comment by plroebuck** [comment]
Line numbers don't match expected, but only place basename is used in CLI is [here](https://github.com/cybertk/abao/blob/20b9357daafb051d6f59db136f9b35b59a1eaa0e/lib/cli.coffee#L35).

For quick test, hardcode the value on line 35 to be:
```js
  prog = 'abao'
```

**Comment by raj-bhagya** [comment]
I hardcoded value to **prog = 'abao'** in line 35, but still same issue.
**macOS 10.13.2**

**Comment by plroebuck** [comment]
I'm running macOS 10.13.4 so OS-wise this code should have no problems.
I was running **Node-8.11.1**, but to test this I upgraded to current development version _without_ any changes to **abao-0.6.0** GitHub release.

```bash
$ node --version
v10.3.0
$ bin/abao --version
0.6.0
```
What is displayed for this command?
```bash
$ which abao
```

**Comment by raj-bhagya** [comment]
$ which abao
`/usr/local/bin/abao`

**Comment by plroebuck** [comment]
Copy'n'paste the `parseArgs` function from "cli.coffee" here.

**Comment by raj-bhagya** [comment]
```
parseArgs = (argv) ->
  'use strict'
  allOptions = _.assign {}, abaoOptions, mochaOptions
  mochaOptionNames = Object.keys mochaOptions
  prog = path.basename pkg.bin
  return yargs(argv)
    .usage("Usage:\n  #{prog} </path/to/raml> [OPTIONS]" +
      "\n\nExample:\n  #{prog} api.raml --server http://api.example.com")
    .options(allOptions)
    .group(mochaOptionNames, 'Options passed to Mocha:')
    .implies('template', 'generate-hooks')
    .check((argv) ->
      if argv.reporters == true
        showReporters()
        process.exit EXIT_SUCCESS

      # Ensure single positional argument present
      if argv._.length < 1
        throw new Error "#{prog}: must specify path to RAML file"
      else if argv._.length > 1
        throw new Error "#{prog}: accepts single positional command-line argument"

      return true
    )
    .wrap(80)
    .help('help', 'Show usage information and exit')
    .version('version', 'Show version number and exit', pkg.version)
    .epilog("Website:\n  #{pkg.homepage}")
    .argv
```

**Comment by plroebuck** [comment]
```js
parseArgs = (argv) ->
  'use strict'
  allOptions = _.assign {}, abaoOptions, mochaOptions
  mochaOptionNames = Object.keys mochaOptions
  prog = path.basename pkg.bin        <--- Thought you changed this line
  return yargs(argv)
    .usage("Usage:\n  #{prog} </path/to/raml> [OPTIONS]" +
      "\n\nExample:\n  #{prog} api.raml --server http://api.example.com")
    .options(allOptions)
...
```

**Comment by raj-bhagya** [comment]
I changed that line and tried. Meantime time I tired to downgrade node version to **8.11.1** and reinstalled abao-0.6.0 (Just to see if there is compatibility problem), that's why it changed back to original state.
Sorry about the confusion. Here is the function code:
```
parseArgs = (argv) ->
  'use strict'
  allOptions = _.assign {}, abaoOptions, mochaOptions
  mochaOptionNames = Object.keys mochaOptions
  prog = 'abao'
  return yargs(argv)
    .usage("Usage:\n  #{prog} </path/to/raml> [OPTIONS]" +
      "\n\nExample:\n  #{prog} api.raml --server http://api.example.com")
    .options(allOptions)
    .group(mochaOptionNames, 'Options passed to Mocha:')
    .implies('template', 'generate-hooks')
    .check((argv) ->
      if argv.reporters == true
        showReporters()
        process.exit EXIT_SUCCESS

      # Ensure single positional argument present
      if argv._.length < 1
        throw new Error "#{prog}: must specify path to RAML file"
      else if argv._.length > 1
        throw new Error "#{prog}: accepts single positional command-line argument"

      return true
    )
    .wrap(80)
    .help('help', 'Show usage information and exit')
    .version('version', 'Show version number and exit', pkg.version)
    .epilog("Website:\n  #{pkg.homepage}")
    .argv
```

[~/repos/simile/simile_web_service/tests/raml → develop]$ npm list --depth=0

> simile@1.0.0 /Users/ramesh/repos/simile
> ├── chai@4.1.2
> └── underscore@1.8.3

**Comment by plroebuck** [comment]
So I'm lost. If the code is changed, how are you still getting the same error referring to `path.basename()`?

**Comment by plroebuck** [comment]
Need this from **abao**'s perspective:
```bash
$ cd /usr/local/lib/node_modules/abao
$ npm list --depth=0
```

**Comment by raj-bhagya** [comment]
[/usr/local/lib/node_modules/abao]$ npm list --depth=0
```
abao@0.6.0 (git+https://git@github.com/cybertk/abao.git#20b9357daafb051d6f59db136f9b35b59a1eaa0e) /usr/local/lib/node_modules/abao
├── async@2.6.1
├── coffee-errors@0.8.6
├── coffee-script@1.12.7
├── csonschema@0.5.3
├── glob@7.1.2
├── lodash@4.17.10
├── mocha@5.2.0
├── mustache@2.3.0
├── proxyquire@2.0.1
├── raml-parser@0.8.18
├── request@2.87.0
├── source-map-support@0.5.6
├── tv4@1.3.0
├── underscore@1.8.3
└── yargs@11.1.0
```
Is there any other occurrence of basename? do I need to build anything after changing that line?

**Comment by raj-bhagya** [comment]
$ abao --version
```
path.js:39
    throw new ERR_INVALID_ARG_TYPE('path', 'string', path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.basename (path.js:1299:5)
    at parseArgs (/usr/local/lib/node_modules/abao/lib/cli.coffee:49:17)
    at Object.main (/usr/local/lib/node_modules/abao/lib/cli.coffee:67:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/abao/bin/abao:15:27)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
```

**Comment by raj-bhagya** [comment]
I got that fixed, there was a problem with my local setup. I was changing basename in one user's library not globally, changed it globally and working fine now. Sorry about that.

$ abao --version
0.6.0

Looks like raml tests are also running fine with `"underscore": "1.8.3"`, I will confirm it soon. thanks!

**Comment by plroebuck** [comment]
Found the `TypeError` problem you had above -- "npm" changes the "bin" field in "package.json" from string to a map when installed. Fix committed.

**Comment by raj-bhagya** [comment]
@plroebuck 
Tests are running now with 0.6.0 version with above fix, thanks.
 Just curious to know when is the Abao 0.6.0 expected to move to stable release?

**Comment by luis-carlos** [comment]
> 
> 
> @plroebuck
> Tests are running now with 0.6.0 version with above fix, thanks.
> Just curious to know when is the Abao 0.6.0 expected to move to stable release?

@raj-bhagya: How can I install Abao 0.6.0?

I tried the following

![image](https://user-images.githubusercontent.com/4765387/62899435-5c321c80-bd1d-11e9-94d6-efd44674db00.png)

but still got 0.5.3
