### ISSUE TITLE
Failed to run abao with mocha exception

### ISSUE THREAD

**Issue by kmejka** [cybertk/abao#29]
Hi,
I've installed abao with ```npm install -g abao``` and I ran it with my raml file. The result for every endpoint is: ```Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.```

I've tried running the same command, with the same raml file on a different machine and it worked fine. I don't know where to start analysing this. Do you have any tips/help?

The whole trace:
```bash
$ abao index.raml http://apiaily.appdev.io/kraken/v2


  GET /schedule/data/{regionId}/broadcasts.json -> 200
    1) Validate response code only

  GET /schedule/data/{regionId}/broadcasts/{ids}.json -> 200
    2) Validate response code only

  GET /schedule/data/{regionId}/videos.json -> 200
    3) Validate response code only

  GET /schedule/data/{regionId}/videos/{id}.json -> 200
    4) Validate response code only

  GET /schedule/data/{regionId}/channels.json -> 200
    5) Validate response code only

  GET /schedule/data/{regionId}/channels/{id}.json -> 200
    6) Validate response code only

  GET /schedule/networks/{regionId}/services.json -> 200
    7) Validate response code only

  GET /schedule/networks/{regionId}/services/{id}.json -> 200
    8) Validate response code only

  GET /schedule/meta/errors.json -> 200
    9) Validate response code only


  0 passing (18s)
  9 failing

  1) GET /schedule/data/{regionId}/broadcasts.json -> 200 Validate response code only:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
    at [object Object].<anonymous> (/usr/local/lib/node_modules/abao/node_modules/mocha/lib/runnable.js:170:19)      
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)                                                         
                                                                                                                     

  2) GET /schedule/data/{regionId}/broadcasts/{ids}.json -> 200 Validate response code only:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
    at [object Object].<anonymous> (/usr/local/lib/node_modules/abao/node_modules/mocha/lib/runnable.js:170:19)      
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)                                                         
  

  3) GET /schedule/data/{regionId}/videos.json -> 200 Validate response code only:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
    at [object Object].<anonymous> (/usr/local/lib/node_modules/abao/node_modules/mocha/lib/runnable.js:170:19)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
  

  4) GET /schedule/data/{regionId}/videos/{id}.json -> 200 Validate response code only:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
    at [object Object].<anonymous> (/usr/local/lib/node_modules/abao/node_modules/mocha/lib/runnable.js:170:19)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
  

  5) GET /schedule/data/{regionId}/channels.json -> 200 Validate response code only:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
    at [object Object].<anonymous> (/usr/local/lib/node_modules/abao/node_modules/mocha/lib/runnable.js:170:19)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
  

  6) GET /schedule/data/{regionId}/channels/{id}.json -> 200 Validate response code only:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
    at [object Object].<anonymous> (/usr/local/lib/node_modules/abao/node_modules/mocha/lib/runnable.js:170:19)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
  

  7) GET /schedule/networks/{regionId}/services.json -> 200 Validate response code only:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
    at [object Object].<anonymous> (/usr/local/lib/node_modules/abao/node_modules/mocha/lib/runnable.js:170:19)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
  

  8) GET /schedule/networks/{regionId}/services/{id}.json -> 200 Validate response code only:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
    at [object Object].<anonymous> (/usr/local/lib/node_modules/abao/node_modules/mocha/lib/runnable.js:170:19)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
  

  9) GET /schedule/meta/errors.json -> 200 Validate response code only:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
    at [object Object].<anonymous> (/usr/local/lib/node_modules/abao/node_modules/mocha/lib/runnable.js:170:19)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

```bash
$ npm ls -g
/usr/local/lib
├─┬ abao@0.3.1
│ ├── async@0.9.0
│ ├─┬ chai@2.2.0
│ │ ├── assertion-error@1.0.0
│ │ └─┬ deep-eql@0.1.3
│ │   └── type-detect@0.1.1
│ ├─┬ chai2-json-schema@1.2.0
│ │ ├── jsonpointer.js@0.3.0
│ │ └── tv4@1.0.18
│ ├── coffee-errors@0.8.6
│ ├── coffee-script@1.9.1
│ ├─┬ csonschema@0.5.1
│ │ └── cson-safe@1.0.5
│ ├─┬ glob@4.5.3
│ │ ├─┬ inflight@1.0.4
│ │ │ └── wrappy@1.0.1
│ │ ├── inherits@2.0.1
│ │ ├─┬ minimatch@2.0.4
│ │ │ └─┬ brace-expansion@1.1.0
│ │ │   ├── balanced-match@0.2.0
│ │ │   └── concat-map@0.0.1
│ │ └─┬ once@1.3.1
│ │   └── wrappy@1.0.1
│ ├─┬ jsonlint@1.6.2
│ │ ├── JSV@4.0.2
│ │ └─┬ nomnom@1.8.1
│ │   ├─┬ chalk@0.4.0
│ │   │ ├── ansi-styles@1.0.0
│ │   │ ├── has-color@0.1.7
│ │   │ └── strip-ansi@0.1.1
│ │   └── underscore@1.6.0
│ ├─┬ mocha@2.2.1
│ │ ├── commander@2.3.0
│ │ ├─┬ debug@2.0.0
│ │ │ └── ms@0.6.2
│ │ ├── diff@1.0.8
│ │ ├── escape-string-regexp@1.0.2
│ │ ├─┬ glob@3.2.3
│ │ │ ├── graceful-fs@2.0.3
│ │ │ ├── inherits@2.0.1
│ │ │ └─┬ minimatch@0.2.14
│ │ │   ├── lru-cache@2.5.0
│ │ │   └── sigmund@1.0.0
│ │ ├── growl@1.8.1
│ │ ├─┬ jade@0.26.3
│ │ │ ├── commander@0.6.1
│ │ │ └── mkdirp@0.3.0
│ │ ├─┬ mkdirp@0.5.0
│ │ │ └── minimist@0.0.8
│ │ └── supports-color@1.2.1
│ ├─┬ optimist@0.6.1
│ │ ├── minimist@0.0.10
│ │ └── wordwrap@0.0.2
│ ├── proxyquire@1.4.0
│ ├─┬ raml-parser@0.8.10
│ │ ├── inflection@1.3.8
│ │ ├── json-lint@0.1.0
│ │ ├── q@0.9.7
│ │ ├── uritemplate@0.3.4
│ │ └── xmlhttprequest@1.6.0
│ ├─┬ request@2.54.0
│ │ ├── aws-sign2@0.5.0
│ │ ├─┬ bl@0.9.4
│ │ │ └─┬ readable-stream@1.0.33
│ │ │   ├── core-util-is@1.0.1
│ │ │   ├── inherits@2.0.1
│ │ │   ├── isarray@0.0.1
│ │ │   └── string_decoder@0.10.31
│ │ ├── caseless@0.9.0
│ │ ├─┬ combined-stream@0.0.7
│ │ │ └── delayed-stream@0.0.5
│ │ ├── forever-agent@0.6.0
│ │ ├── form-data@0.2.0
│ │ ├─┬ har-validator@1.4.0
│ │ │ ├── bluebird@2.9.15
│ │ │ ├─┬ chalk@1.0.0
│ │ │ │ ├── ansi-styles@2.0.1
│ │ │ │ ├── escape-string-regexp@1.0.3
│ │ │ │ ├─┬ has-ansi@1.0.3
│ │ │ │ │ ├── ansi-regex@1.1.1
│ │ │ │ │ └── get-stdin@4.0.1
│ │ │ │ ├─┬ strip-ansi@2.0.1
│ │ │ │ │ └── ansi-regex@1.1.1
│ │ │ │ └── supports-color@1.3.1
│ │ │ ├─┬ commander@2.7.1
│ │ │ │ └── graceful-readlink@1.0.1
│ │ │ ├─┬ debug@2.1.3
│ │ │ │ └── ms@0.7.0
│ │ │ ├─┬ is-my-json-valid@2.10.0
│ │ │ │ ├── generate-function@2.0.0
│ │ │ │ ├─┬ generate-object-property@1.1.1
│ │ │ │ │ └── is-property@1.0.2
│ │ │ │ ├── jsonpointer@1.1.0
│ │ │ │ └── xtend@4.0.0
│ │ │ └── require-directory@2.1.0
│ │ ├─┬ hawk@2.3.1
│ │ │ ├── boom@2.6.1
│ │ │ ├── cryptiles@2.0.4
│ │ │ ├── hoek@2.12.0
│ │ │ └── sntp@1.0.9
│ │ ├─┬ http-signature@0.10.1
│ │ │ ├── asn1@0.1.11
│ │ │ ├── assert-plus@0.1.5
│ │ │ └── ctype@0.5.3
│ │ ├── isstream@0.1.2
│ │ ├── json-stringify-safe@5.0.0
│ │ ├─┬ mime-types@2.0.10
│ │ │ └── mime-db@1.8.0
│ │ ├── node-uuid@1.4.3
│ │ ├── oauth-sign@0.6.0
│ │ ├── qs@2.4.1
│ │ ├── stringstream@0.0.4
│ │ ├─┬ tough-cookie@0.12.1
│ │ │ └── punycode@1.3.2
│ │ └── tunnel-agent@0.4.0
│ └── underscore@1.8.2
```

**Comment by kmejka** [comment]
I found the problem, I had no connection to the target server. Closing.
