### ISSUE TITLE
Error from csonschema

### ISSUE THREAD

**Issue by emanuelef** [cybertk/abao#56]
I'm trying to run abao on my RAML, the RAML should be ok cause I'm also using other tools on it.
I get an error probably because I have a schema with type array, it's a valid json schema I tested with validators. Unfortunately the stack trace doesn't say exactly where the problem occurred in the RAML file.

$ abao vSTB.raml http://localhost:3333
/usr/local/lib/node_modules/abao/node_modules/csonschema/lib/index.js:235
          throw error;
          ^

Error: Type is not defined: array
    at _parseCustomizedType (/usr/local/lib/node_modules/abao/node_modules/csonschema/lib/index.js:27:13)
    at _parseString (/usr/local/lib/node_modules/abao/node_modules/csonschema/lib/index.js:155:16)
    at _parseField (/usr/local/lib/node_modules/abao/node_modules/csonschema/lib/index.js:48:14)
    at _parseObj (/usr/local/lib/node_modules/abao/node_modules/csonschema/lib/index.js:75:25)
    at _parseField (/usr/local/lib/node_modules/abao/node_modules/csonschema/lib/index.js:46:14)
    at _parseFromObj (/usr/local/lib/node_modules/abao/node_modules/csonschema/lib/index.js:220:18)
    at Object.parse (/usr/local/lib/node_modules/abao/node_modules/csonschema/lib/index.js:255:25)
    at parseSchema (/usr/local/lib/node_modules/abao/lib/add-tests.coffee:14:25)
    at /usr/local/lib/node_modules/abao/lib/add-tests.coffee:82:36
    at /usr/local/lib/node_modules/abao/node_modules/async/lib/async.js:122:13
    at _each (/usr/local/lib/node_modules/abao/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/usr/local/lib/node_modules/abao/node_modules/async/lib/async.js:121:9)
    at /usr/local/lib/node_modules/abao/lib/add-tests.coffee:58:20
    at /usr/local/lib/node_modules/abao/node_modules/async/lib/async.js:122:13
    at _each (/usr/local/lib/node_modules/abao/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/usr/local/lib/node_modules/abao/node_modules/async/lib/async.js:121:9)
    at addTests (/usr/local/lib/node_modules/abao/lib/add-tests.coffee:40:18)
    at /usr/local/lib/node_modules/abao/lib/abao.coffee:47:18
    at fn (/usr/local/lib/node_modules/abao/node_modules/async/lib/async.js:638:34)
    at Immediate._onImmediate (/usr/local/lib/node_modules/abao/node_modules/async/lib/async.js:554:34)
    at processImmediate [as _immediateCallback] (timers.js:374:17)

**Comment by cybertk** [comment]
Did you set schema to jsonschema explicitly?

**Comment by emanuelef** [comment]
it must something in my RAML, I've seen a similar example in the test and it works there.
I'll investigate more but must be on my side.
Thanks

**Comment by emanuelef** [comment]
I managed to replicate it on a smaller RAML, if this is of interest I can put the zip somewhere.
The main part is:

`
schemas:
  - devices: !include schemas/devices.json
resourceTypes: !include resourceTypes/common-types.raml
/devices:
  type:
    collection-devices:
     exampleCollection: !include static_examples/devices.json
`

**Comment by cybertk** [comment]
Please share RAML

**Comment by emanuelef** [comment]
I put it temporarily here:
https://dl.dropboxusercontent.com/u/146722192/usecase.zip

**Comment by plroebuck** [comment]
Is this issue unresolved?

**Comment by galk-in** [comment]
@emanuelef 
I checked your raml. At `schemas/devices.json` you haven't 
```    "$schema": "http://json-schema.org/draft-04/schema#",```
