### ISSUE TITLE
Duplicate URI

### ISSUE THREAD

**Issue by ProLoser** [cybertk/abao#68]
This is what I'm seeing when I try to use abao for the first time. No idea what I'm doing wrong:

```bash
abao -f "hooks/*" _browse.raml /browse/items/{browse_type}/filter/{filter_type}/sort/{sort_method}/offset/{offset}/size/{size}
Found Hookfiles: hooks/browse.js


  GET /browse/items/{browse_type}/filter/{filter_type}/sort/{sort_method}/offset/{offset}/size/{size} -> 200
    1) Validate response code only


  0 passing (12ms)
  1 failing

  1) GET /browse/items/{browse_type}/filter/{filter_type}/sort/{sort_method}/offset/{offset}/size/{size} -> 200 Validate response code only:
     Uncaught AssertionError: expected [Error: Invalid URI "/browse/items/browse_type/filter/filter_type/sort/sort_method/offset/offset/size/size/browse/items/undefined/filter/undefined/sort/undefined/offset/undefined/size/undefined"] to equal null
    at Function.assert.isNull (/usr/local/lib/node_modules/chai/lib/chai/interface/assert.js:388:32)
    at Test.assertResponse (/usr/local/lib/node_modules/abao/lib/test.js:86:14)
    at /usr/local/lib/node_modules/abao/lib/test.js:3:59
    at /usr/local/lib/node_modules/abao/lib/test.js:70:11
    at fn (/usr/local/lib/node_modules/abao/node_modules/async/lib/async.js:638:34)
    at Immediate._onImmediate (/usr/local/lib/node_modules/abao/node_modules/async/lib/async.js:554:34)
```

Note that the invalid URI is essentially twice as long as it should be and the second half contains null values

**Comment by ProLoser** [comment]
Okay so now I finally understand that what you're expecting me to send is the `baseUri`, NOT the action I want to test. That said, why is it I have to specify my own host if the raml file supplies a `baseUri`?

**Comment by ProLoser** [comment]
Duplicate of #25
