### ISSUE TITLE
Cannot find module 'chai'

### ISSUE THREAD

**Issue by raafael911** [cybertk/abao#93]
When I do a fresh installation of abao with `npm install -g abao` and I execute any abao command (for example `abao --version`) I get the following output:

> module.js:339
    throw err;
    ^
Error: Cannot find module 'chai'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/lib/node_modules/abao/lib/abao.coffee:12:10)
    at Object.<anonymous> (/usr/lib/node_modules/abao/lib/abao.coffee:67:4)
    at Module._compile (module.js:435:26)
    at Object.loadFile (/usr/lib/node_modules/abao/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
    at Module.load (/usr/lib/node_modules/abao/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/lib/node_modules/abao/bin/abao:8:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3

After I installed chai manually with `npm i -g chai`, abao works normally.

My environment is:
> $ nodejs --version
v4.2.0
$ npm --version
2.14.7

**Comment by raafael911** [comment]
This issue is already fixed in 1adbb38.

**Comment by jeppe1990** [comment]
I just tried to run abao and I got the same error. I have run "npm update -g abao" to ensure, I have the latest package. 
Is this still an issue? Or do I need a specific version of abao that on npm?
![Console output](https://cloud.githubusercontent.com/assets/17174187/14168703/13c232c2-f724-11e5-8841-923e309e7171.png)

**Comment by plroebuck** [comment]
Not to knowledge. But you didn't provide any information about your setup.
Sure you're running current version?

```bash
$ abao --version
```

**Comment by jeppe1990** [comment]
My version is 2.14.20. I am not sure what the most current version is. I removed abao and installed the github:cybertk/abao version. Now it doesn't throw any errors. Well, it throws errors, but they are validation errors ;)

**Comment by plroebuck** [comment]
Not following your given version (as **abao** is 0.4.0beta6), but sounds like it's working for you now.

**Comment by jeppe1990** [comment]
Yeah i just checked again. I don't know where I got that other number from :P
